var T=Object.create;var p=Object.defineProperty;var E=Object.getOwnPropertyDescriptor;var P=Object.getOwnPropertyNames;var V=Object.getPrototypeOf,L=Object.prototype.hasOwnProperty;var w=t=>p(t,"__esModule",{value:!0});var M=(t,e)=>{w(t);for(var r in e)p(t,r,{get:e[r],enumerable:!0})},R=(t,e,r)=>{if(e&&typeof e=="object"||typeof e=="function")for(let o of P(e))!L.call(t,o)&&o!=="default"&&p(t,o,{get:()=>e[o],enumerable:!(r=E(e,o))||r.enumerable});return t},c=t=>R(w(p(t!=null?T(V(t)):{},"default",t&&t.__esModule&&"default"in t?{get:()=>t.default,enumerable:!0}:{value:t,enumerable:!0})),t);M(exports,{default:()=>q});var A=c(require("atom"));var U=c(require("path"));var n=[];for(let t=0;t<256;++t)n.push((t+256).toString(16).slice(1));function b(t,e=0){return(n[t[e+0]]+n[t[e+1]]+n[t[e+2]]+n[t[e+3]]+"-"+n[t[e+4]]+n[t[e+5]]+"-"+n[t[e+6]]+n[t[e+7]]+"-"+n[t[e+8]]+n[t[e+9]]+"-"+n[t[e+10]]+n[t[e+11]]+n[t[e+12]]+n[t[e+13]]+n[t[e+14]]+n[t[e+15]]).toLowerCase()}var k=c(require("crypto")),d=new Uint8Array(256),m=d.length;function h(){return m>d.length-16&&((0,k.randomFillSync)(d),m=0),d.slice(m,m+=16)}var j=c(require("crypto")),f={randomUUID:j.randomUUID};function H(t,e,r){if(f.randomUUID&&!e&&!t)return f.randomUUID();t=t||{};let o=t.random??t.rng?.()??h();if(o.length<16)throw new Error("Random bytes length must be >= 16");if(o[6]=o[6]&15|64,o[8]=o[8]&63|128,e){if(r=r||0,r<0||r+16>e.length)throw new RangeError(`UUID byte range ${r}:${r+15} is out of buffer bounds`);for(let s=0;s<16;++s)e[r+s]=o[s];return e}return b(o)}var y=H;var D="service-cron";function i(t,e){for(var r=0,o=e.length,s=t.length;r<o;r++,s++)t[s]=e[r];return t}var $=function(){function t(e){e===void 0&&(e={}),this.name=e.name,this.styleSheet=`
      background-color: `+(e.backgroundColor||"darkgrey")+`;
      border-radius: 2px;
      color: `+(e.color||"white")+`;
      line-height: 1.5;
      padding: 1px 4px;
      text-shadow: 0 1px 0px rgba(0, 0, 0, 0.2);
    `}return t.prototype.__console__=function(e){for(var r,o=[],s=1;s<arguments.length;s++)o[s-1]=arguments[s];!(atom==null?void 0:atom.inDevMode())||(o.unshift("%c"+this.name+"%c",this.styleSheet,""),(r=window.console)[e].apply(r,o))},t.prototype.debug=function(){for(var e=[],r=0;r<arguments.length;r++)e[r]=arguments[r];this.__console__.apply(this,i(["debug"],e))},t.prototype.error=function(){for(var e=[],r=0;r<arguments.length;r++)e[r]=arguments[r];this.__console__.apply(this,i(["error"],e))},t.prototype.info=function(){for(var e=[],r=0;r<arguments.length;r++)e[r]=arguments[r];this.__console__.apply(this,i(["info"],e))},t.prototype.log=function(){for(var e=[],r=0;r<arguments.length;r++)e[r]=arguments[r];this.__console__.apply(this,i(["log"],e))},t.prototype.trace=function(){for(var e=[],r=0;r<arguments.length;r++)e[r]=arguments[r];this.__console__.apply(this,i(["trace"],e))},t.prototype.warn=function(){for(var e=[],r=0;r<arguments.length;r++)e[r]=arguments[r];this.__console__.apply(this,i(["warn"],e))},t}(),C=$;var a=new C({name:D,backgroundColor:"black",color:"paleturquoise"});var _=new Worker((0,U.resolve)(__dirname,"cron.worker.js"));function W(t){return new Promise((e,r)=>{let o=y(),s={view:"atom-workspace",...t};a.log("Registering cronjob",s),_.postMessage({...s,senderID:o}),_.onmessage=async x=>{if(o!==x.data.recipientID)return;let{commands:u,view:g}=x.data,v;switch(g){case"atom-workspace":v=atom.views.getView(atom.workspace);break;case"atom-text-editor":v=atom.views.getView(atom.workspace.getActiveTextEditor());break;default:throw Error(`Cannot dispatch commands to unsupported view ${g}`)}let S=Array.isArray(u)?u:[u];try{S.map(l=>{a.log("Dispatching command",{command:l,view:g}),atom.commands.dispatch(v,l)})}catch(l){r(l)}e(!0)}})}var I=W;var q={subscriptions:new A.CompositeDisposable,activate(){a.log("Activating package")},deactivate(){a.log("Deactivating package"),this.subscriptions?.dispose()},provideCron(){return a.log("Providing service"),I}};0&&(module.exports={});
/*! *****************************************************************************
Copyright (c) Microsoft Corporation.

Permission to use, copy, modify, and/or distribute this software for any
purpose with or without fee is hereby granted.

THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES WITH
REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY
AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY SPECIAL, DIRECT,
INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM
LOSS OF USE, DATA OR PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR
OTHER TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR
PERFORMANCE OF THIS SOFTWARE.
***************************************************************************** */
//# sourceMappingURL=main.js.map
